umdlib_ui_pattern_sources.date:
  type: mapping
  label: 'Source: Date'
  mapping:
    value:
      type: date
      label: 'Date'
umdlib_ui_pattern_sources.format:
  type: mapping
  label: 'Source: Format'
  mapping:
    value:
      type: string
      label: 'Format'

umdlib_ui_pattern_sources.search_endpoint:
  type: mapping
  label: 'Source: Search Endpoint'
  mapping:
    value:
      type: string
      label: 'Endpoint'
umdlib_ui_pattern_sources.search_facet:
  type: mapping
  label: 'Source: Search Facet'
  mapping:
    value:
      type: string
      label: 'Facet'
